name: Edit Issue
on:
  issues:
    types:
      - opened

jobs:
  add-assign:
    uses: shinGangan/.github/.github/workflows/issue.yml@main
    permissions:
      contents: read
      repository-projects: read
      issues: write
    with:
      number: ${{ github.event.issue.number }}
      title: ${{ github.event.issue.title }}
      milestone: 'v0.1.0'
      assignee: ${{ github.actor }}
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
      repo: ${{ github.repository }}
